services:
    auth-frontend:
        build:
            context: ./frontend/auth
            args:
                VITE_API_URL: http://localhost:4000
        container_name: auth-frontend
        restart: always
        ports:
            - "10000:80"
        networks:
            - urban-flow-network

    user-frontend:
        build:
            context: ./frontend/user
            args:
                VITE_API_URL: http://localhost:4000
                VITE_AUTH_URL: http://localhost:10000
        container_name: user-frontend
        restart: always
        ports:
            - "10006:80"
        networks:
            - urban-flow-network

    monitoring-frontend:
        build:
            context: ./frontend/monitoring
            args:
                VITE_API_URL: http://localhost:4000
                VITE_PROMETHEUS_URL: http://localhost:9090
                VITE_AUTH_URL: http://localhost:10000
        container_name: monitoring-frontend
        restart: always
        ports:
            - "10005:80"
        networks:
            - urban-flow-network

    incidents-frontend:
        build:
            context: ./frontend/incidents
            args:
                VITE_API_URL: http://localhost:4000
                VITE_AUTH_URL: http://localhost:10000
        container_name: incidents-frontend
        restart: always
        ports:
            - "10004:80"
        networks:
            - urban-flow-network

networks:
    urban-flow-network:
        driver: bridge
