services:

  user-database:
    image: postgres:15
    env_file:
      - .env.docker.auth
    ports:
      - "5001:5432"
    volumes:
      - user-database:/var/lib/postgresql/data
    networks:
      - urban-flow-network

  auth-service:
    build: ./modules/auth
    env_file:
      - .env.docker.auth
    ports:
      - "4001:3000"
    depends_on:
      - user-database
    networks:
      - urban-flow-network

volumes:
  user-database:

networks:
  urban-flow-network:
    driver: bridge