services:
    monitoring-frontend:
        build:
            args:
                VITE_API_URL: http://localhost:4000
                VITE_AUTH_URL: http://localhost:10000

    auth-frontend:
        build:
            args:
                VITE_API_URL: http://localhost:4000
