services:

  # External
  rabbitmq:
    image: rabbitmq:3-management
    container_name: RABBIT_MQ
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env.docker.rabbitmq
    networks:
      - urban-flow-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Databases
  user-database:
    image: postgres:15
    container_name: user-database
    env_file:
      - .env.docker.user
    ports:
      - "5006:5432"
    volumes:
      - user-database:/var/lib/postgresql/data
    networks:
      - urban-flow-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  logs-database:
    image: postgres:15
    container_name: logs-database
    env_file:
      - .env.docker.logs
    ports:
      - "5002:5432"
    volumes:
      - logs-database:/var/lib/postgresql/data
    networks:
      - urban-flow-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Services
  auth-service:
    build: ./modules/auth
    container_name: auth-service
    env_file:
      - .env.docker.auth
    ports:
      - "4001:4001"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - urban-flow-network

  user-service:
    build: ./modules/user
    container_name: user-service
    env_file:
      - .env.docker.user
    ports:
      - "4006:4006"
    depends_on:
      user-database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - urban-flow-network

  logs-service:
    build: ./modules/logs
    container_name: logs-service
    env_file:
      - .env.docker.logs
    ports:
      - "4002:4002"
    depends_on:
      logs-database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - urban-flow-network

  gateway-service:
    build: ./modules/gateway
    container_name: gateway-service
    env_file:
      - .env.docker.gateway
    ports:
      - "4000:4000"
    depends_on:      
      rabbitmq:
        condition: service_healthy
    networks:
      - urban-flow-network

volumes:
  user-database:
  logs-database:

networks:
  urban-flow-network:
    driver: bridge