apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: urbanflow
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - name: http
      port: 4001
      targetPort: 4001
    - name: tcp
      port: 6001
      targetPort: 6001
